<div> 
<h1> NumPy </h1>
<a href="https://numpy.org">Visit the Source Website</a>
</div>

<h4> NumPy (Numerical Python) is an open source Python library that’s widely used in science and engineering. The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional ndarray, and a large library of functions that operate efficiently on these data structures
</h4>

In [6]:
import numpy as np

<h4> one dimension array: </h4>

In [8]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

<h4> To access an individual element, use the integer index of the element within square brackets. </h4>

In [15]:
a[0]

1

In [25]:
a[:3]

array([1, 2, 3])

In [27]:
a[2:]

array([3, 4, 5, 6])

<h4> Two- and higher-dimensional arrays: </h4>

In [38]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

<h4> In NumPy, a dimension of an array is sometimes referred to as an “axis” </h4>

<h2> Array attributes</h2>

In [58]:
a.ndim

2

In [60]:
a.shape

(3, 4)

In [67]:
len(a.shape) == a.ndim

True

In [69]:
a.size

12

In [71]:
a.dtype

dtype('int32')

<h2> How to create a basic array </h2>

In [91]:
np.zeros(4)

array([0., 0., 0., 0.])

In [93]:
np.zeros([4,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [95]:
np.ones(3)

array([1., 1., 1.])

In [97]:
np.empty(2)

array([4.24399158e-314, 8.48798317e-314])

In [109]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [113]:
np.arange(5, 15, 3)

array([ 5,  8, 11, 14])

In [121]:
np.linspace(0,5,num = 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [125]:
x = np.ones(4, dtype=np.int64)
x

array([1, 1, 1, 1], dtype=int64)

<h2> Adding, removing, and sorting elements </h2>

In [148]:
x = np.array([9,4,5,1,6,7,8,9])
np.sort(x)
#which returns a sorted copy of an array

array([1, 4, 5, 6, 7, 8, 9, 9])

In [159]:
 y = np.array([[6,2,4],
              [5,2,8],
              [7,3,4]])

In [162]:
np.sort(y, axis=None)

array([2, 2, 3, 4, 4, 5, 6, 7, 8])

In [164]:
np.sort(y, axis=1)

array([[2, 4, 6],
       [2, 5, 8],
       [3, 4, 7]])

In [176]:
x = np.array([3,5,7,8])
y = np.array([4,6,8,9])
np.concatenate((x,y))

array([3, 5, 7, 8, 4, 6, 8, 9])

<h2> Reshaping & Transposing </h2>

In [386]:
a = np.array([[1,2,3,4],
              [3,4,5,6],
              [6,7,8,9]])
a

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [6, 7, 8, 9]])

In [388]:
a.reshape(6,2)

array([[1, 2],
       [3, 4],
       [3, 4],
       [5, 6],
       [6, 7],
       [8, 9]])

In [390]:
a.T

array([[1, 3, 6],
       [2, 4, 7],
       [3, 5, 8],
       [4, 6, 9]])

<h2> Indexing and slicing </h2>

In [238]:
a = np.array([[1,2,3,4],
              [3,4,5,6],
              [6,7,8,9]])

In [224]:
a[1:3]

array([[3, 4, 5, 6],
       [6, 7, 8, 9]])

In [228]:
a[:,1]

array([2, 4, 7])

In [230]:
a[:, [1]]

array([[2],
       [4],
       [7]])

In [278]:
a[0:2,2:]

array([[3, 4],
       [5, 6]])

In [280]:
a[a<5]

array([1, 2, 3, 4, 3, 4])

<h2> creating an array from existing data </h2>

In [303]:
x = np.array([[1,2,3,4,5,6],
             [4,5,6,7,8,9]])

In [309]:
#slicing
x[1,:3]

array([4, 5, 6])

In [311]:
y =np.array([[1,2,3,4,5,6],
             [4,5,6,7,8,9],
             [4,5,6,7,8,9]])

In [319]:
xx=np.vstack([x,y])
xx

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9],
       [4, 5, 6, 7, 8, 9]])

In [330]:
a =np.array([1,2])
b = np.array([2,4,4,5])
np.hstack([a,b])

array([1, 2, 2, 4, 4, 5])

In [350]:
xx = np.arange(10).reshape(2,5)
xx

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [352]:
xx.copy()

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

<h2> Operations </h2>

In [368]:
a = np.array([1,2,3,4])
a.sum()

10

In [370]:
b = np.array([5,6,7,8])

In [372]:
a+b

array([ 6,  8, 10, 12])

In [374]:
x = np.array([[1,2],
             [3,4]])
x.sum()

10

In [376]:
x.sum(axis=0)

array([4, 6])

In [392]:
x.sum(axis=1)

array([3, 7])

In [394]:
x.max()

4

In [396]:
x.min()

1